cities = ['aberdeen', 'abilene', 'akron', 'albany', 'albuquerque', 'alexandria',
          'allentown', 'amarillo', 'anaheim', 'anchorage', 'ann arbor', 'antioch',
          'apple valley', 'appleton', 'arlington', 'arvada', 'asheville', 'athens',
          'atlanta', 'atlantic city', 'augusta', 'aurora', 'austin', 'bakersfield',
          'baltimore', 'barnstable', 'baton rouge', 'beaumont', 'bel air', 'bellevue',
          'berkeley', 'bethlehem', 'billings', 'birmingham', 'bloomington', 'boise',
          'boise city', 'bonita springs', 'boston', 'boulder', 'bradenton', 'bremerton',
          'bridgeport', 'brighton', 'brownsville', 'bryan', 'buffalo', 'burbank',
          'burlington', 'cambridge', 'canton', 'cape coral', 'carrollton', 'cary',
          'cathedral city', 'cedar rapids', 'champaign', 'chandler', 'charleston',
          'charlotte', 'chattanooga', 'chesapeake', 'chicago', 'chula vista',
          'cincinnati', 'clarke county', 'clarksville', 'clearwater', 'cleveland',
          'college station', 'colorado springs', 'columbia', 'columbus', 'concord',
          'coral springs', 'corona', 'corpus christi', 'costa mesa', 'dallas', 'daly city',
          'danbury', 'davenport', 'davidson county', 'dayton', 'daytona beach', 'deltona',
          'denton', 'denver', 'des moines', 'detroit', 'downey', 'duluth', 'durham',
          'el monte', 'el paso', 'elizabeth', 'elk grove', 'elkhart', 'erie', 'escondido',
          'eugene', 'evansville', 'fairfield', 'fargo', 'fayetteville', 'fitchburg',
          'flint', 'fontana', 'fort collins', 'fort lauderdale', 'fort smith',
          'fort walton beach', 'fort wayne', 'fort worth', 'frederick', 'fremont',
          'fresno', 'fullerton', 'gainesville', 'garden grove', 'garland', 'gastonia',
          'gilbert', 'glendale', 'grand prairie', 'grand rapids', 'grayslake', 'green bay',
          'greenbay', 'greensboro', 'greenville', 'gulfport-biloxi', 'hagerstown',
          'hampton', 'harlingen', 'harrisburg', 'hartford', 'havre de grace', 'hayward',
          'hemet', 'henderson', 'hesperia', 'hialeah', 'hickory', 'high point', 'hollywood',
          'honolulu', 'houma', 'houston', 'howell', 'huntington', 'huntington beach',
          'huntsville', 'independence', 'indianapolis', 'inglewood', 'irvine', 'irving',
          'jackson', 'jacksonville', 'jefferson', 'jersey city', 'johnson city', 'joliet',
          'kailua', 'kalamazoo', 'kaneohe', 'kansas city', 'kennewick', 'kenosha', 'killeen',
          'kissimmee', 'knoxville', 'lacey', 'lafayette', 'lake charles', 'lakeland',
          'lakewood', 'lancaster', 'lansing', 'laredo', 'las cruces', 'las vegas',
          'layton', 'leominster', 'lewisville', 'lexington', 'lincoln', 'little rock',
          'long beach', 'lorain', 'los angeles', 'louisville', 'lowell', 'lubbock',
          'macon', 'madison', 'manchester', 'marina', 'marysville', 'mcallen', 'mchenry',
          'medford', 'melbourne', 'memphis', 'merced', 'mesa', 'mesquite', 'miami',
          'milwaukee', 'minneapolis', 'miramar', 'mission viejo', 'mobile', 'modesto',
          'monroe', 'monterey', 'montgomery', 'moreno valley', 'murfreesboro', 'murrieta',
          'muskegon', 'myrtle beach', 'naperville', 'naples', 'nashua', 'nashville',
          'new bedford', 'new haven', 'new london', 'new orleans', 'new york',
          'new york city', 'newark', 'newburgh', 'newport news', 'norfolk', 'normal',
          'norman', 'north charleston', 'north las vegas', 'north port', 'norwalk',
          'norwich', 'oakland', 'ocala', 'oceanside', 'odessa', 'ogden', 'oklahoma city',
          'olathe', 'olympia', 'omaha', 'ontario', 'orange', 'orem', 'orlando',
          'overland park', 'oxnard', 'palm bay', 'palm springs', 'palmdale', 'panama city',
          'pasadena', 'paterson', 'pembroke pines', 'pensacola', 'peoria', 'philadelphia',
          'phoenix', 'pittsburgh', 'plano', 'pomona', 'pompano beach', 'port arthur',
          'port orange', 'port saint lucie', 'port st. lucie', 'portland', 'portsmouth',
          'poughkeepsie', 'providence', 'provo', 'pueblo', 'punta gorda', 'racine',
          'raleigh', 'rancho cucamonga', 'reading', 'redding', 'reno', 'richland',
          'richmond', 'richmond county', 'riverside', 'roanoke', 'rochester', 'rockford',
          'roseville', 'round lake beach', 'sacramento', 'saginaw', 'saint louis',
          'saint paul', 'saint petersburg', 'salem', 'salinas', 'salt lake city',
          'san antonio', 'san bernardino', 'san buenaventura', 'san diego', 'san francisco',
          'san jose', 'santa ana', 'santa barbara', 'santa clara', 'santa clarita',
          'santa cruz', 'santa maria', 'santa rosa', 'sarasota', 'savannah', 'scottsdale',
          'scranton', 'seaside', 'seattle', 'sebastian', 'shreveport', 'simi valley',
          'sioux city', 'sioux falls', 'south bend', 'south lyon', 'spartanburg', 'spokane',
          'springdale', 'springfield', 'st. louis', 'st. paul', 'st. petersburg', 'stamford',
          'sterling heights', 'stockton', 'sunnyvale', 'syracuse', 'tacoma', 'tallahassee',
          'tampa', 'temecula', 'tempe', 'thornton', 'thousand oaks', 'toledo', 'topeka',
          'torrance', 'trenton', 'tucson', 'tulsa', 'tuscaloosa', 'tyler', 'utica', 'vallejo',
          'vancouver', 'vero beach', 'victorville', 'virginia beach', 'visalia', 'waco',
          'warren', 'washington', 'waterbury', 'waterloo', 'west covina', 'west valley city',
          'westminster', 'wichita', 'wilmington', 'winston', 'winter haven', 'worcester',
          'yakima', 'yonkers', 'york', 'youngstown']

airports = ['aberdeen regional airport', 'abilene regional airport', 'abraham lincoln capital airport',
            'adak airport', 'adirondack regional airport', 'aguadilla airport', 'akron-canton airport',
            'alakanuk airport', 'alamogordo-white sands regional airport', 'albany international airport',
            'albuquerque international sunport', 'alexandria international airport', 'allegheny county airport',
            'allen aaf airport', 'alliance municipal airport', 'alpena county regional airport',
            'altoona-blair county airport', 'amarillo international airport', 'ambler airport',
            'anacortes airport', 'anaktuvuk pass airport', 'anchorage international airport',
            'anderson municipal airport', 'anderson regional airport', 'angoon seaplane base',
            'aniak airport', 'anniston municipal airport', 'arcata airport', 'arnold palmer regional airport',
            'asheville regional airport', 'aspen-pitkin county airport', 'astoria regional airport',
            'athens ben epps airport', 'atlanta international airport', 'atlantic city international airport',
            'atlantic city municipal airport bader field', 'atqasuk edward burnell sr memorial airport',
            'augusta regional airport', 'augusta state airport', 'austin straubel international airport',
            'austin-bergstrom international airport', 'baltimore   washington international airport',
            'bangor international airport', 'barnes municipal airport', 'barnstable municipal airport',
            'barter island lrrs airport', 'baton rouge international airport', 'baudette international airport',
            'baxter county regional airport', 'bedford hanscom field', 'bellaire antrim county airport',
            'bellingham international airport', 'bemidji regional airport', 'bert mooney airport',
            'bethel airport', 'billings logan international airport', 'birmingham international airport',
            'bishop international airport', 'bismarck municipal airport', 'block island state airport',
            'blue grass airport', 'bob baker memorial airport', 'boeing field king county international airport',
            'boise airport', 'boone county airport', 'boston logan international airport',
            'bowling green-warren county regional airport', 'bozeman gallatin field airport',
            'bradford regional airport', 'bradley international airport', 'brainerd lakes regional airport',
            'brazoria county airport', 'bremerton national airport', 'brookings municipal airport',
            'brownsville south padre island international airport', 'brunswick golden isles airport',
            'bryce canyon airport', 'buchanan field airport', 'buckland airport',
            'buffalo niagara international airport', 'burbank bob hope airport', 'burke lakefront airport',
            'burlington international airport', 'bush intercontinental airport', 'canyonlands field',
            'cape girardeau regional airport', 'cape may county airport', 'carl r keller field',
            'cavern city air terminal', 'cecil field airport', 'cedar city regional airport',
            'cedar rapids eastern iowa airport', 'central illinois regional airport',
            'central nebraska regional airport', 'central wisconsin airport', 'champaign willard airport',
            'chan gurney municipal airport', 'chandler field airport', 'charles b. wheeler downtown airport',
            'charleston international airport', 'charleston yeager airport', 'charlevoix municipal airport',
            'charlotte county airport', 'charlotte douglas international airport',
            'charlottesville-albemarle airport', 'chattanooga metropolitan airport',
            'chautauqua county jamestown airport', 'chefornak airport', 'cherry capital airport',
            'chevak airport', 'cheyenne regional airport', 'chicago midway airport',
            "chicago o'hare international airport", 'chico municipal airport', 'chippewa county international airport',
            'chippewa valley regional airport', 'chisholm-hibbing airport',
            'cincinnati municipal airport lunken field', 'cincinnati   northern kentucky international airport',
            'cleveland hopkins international airport', 'clinton county airport', 'clinton municipal airport',
            "coeur d'alene airport", 'cold bay airport', 'coles county memorial airport', 'colorado springs airport',
            'columbia metropolitan airport', 'columbia regional airport', 'columbus metropolitan airport',
            'columbus municipal airport', 'cordova municipal airport', 'corpus christi international airport',
            'cortez municipal airport', 'corvallis municipal airport', 'craig airport',
            'craven county regional airport', 'culebra airport', 'cuyahoga county airport',
            'cyril e king airport', 'dallas love field', 'dallas fort worth international airport',
            'danbury municipal airport', 'dane county regional airport', 'danville regional airport',
            'dare county regional airport', 'dayton international airport', 'daytona beach international airport',
            'deadhorse airport', 'decatur airport', 'deer valley municipal airport', 'del rio international airport',
            'delaware county airport', 'delta county airport', 'denver international airport',
            'des moines international airport', 'detroit city airport', 'detroit metro airport',
            'devils lake municipal airport', 'dickinson - theodore roosevelt regional airport',
            'diego jimenez torres airport', 'dillingham airport', 'dodge city regional airport',
            'donaldson center airport', 'dothan regional airport', 'downtown manhattan heliport',
            'drake field', 'draughon-miller central texas regional airport', 'du bois-jefferson county airport',
            'dubuque regional airport', 'duluth international airport', 'durango-la plata county airport',
            'dutchess county airport', 'eagle county regional airport', 'east texas regional airport',
            'eastern oregon regional airport at pendleton', 'easterwood airport', 'edward f. knapp state airport',
            'edward g. pitka sr airport', 'eek airport', 'el paso international airport', 'elim airport',
            'elkhart municipal airport', 'elko regional airport', 'ellington field',
            'elmira   corning regional airport', 'ely airport', 'ely municipal airport', 'emmonak airport',
            'english bay airport', 'eppley airfield', 'erie international airport', 'ernest a. love field airport',
            'esler regional airport', 'essex county airport', 'eugene airport', 'evansville regional airport',
            'fairbanks international airport', 'fairmont municipal airport', 'falls international airport',
            'fayetteville regional grannis field airport', 'fernando luis ribas dominicci airport', 'fitiuta airport',
            'flagstaff pulliam airport', 'florence regional airport', 'florida keys marathon airport',
            'floyd bennett memorial airport', 'forbes field airport', 'fort collins-loveland municipal airport',
            'fort dodge regional airport', 'fort lauderdale hollywood international airport', 'fort smith airport',
            'fort walton beach airport', 'fort wayne international airport', 'fort worth meacham international airport',
            'fort yukon airport', 'four corners regional airport', 'fresno air terminal', 'friday harbor airport',
            'friedman memorial airport', 'gainesville regional airport', 'galbraith lake airport',
            'gallup municipal airport', 'galveston scholes international airport', 'gambell airport',
            'garden city regional airport', 'gary regional airport', 'gaylord regional airport',
            'general mitchell international airport', 'gerald r. ford international airport',
            'gillette-campbell county airport', 'glacier park international airport', 'gogebic-iron county airport',
            'golden triangle regional airport', 'golovin airport', 'goodland municipal airport',
            'grand canyon national park airport', 'grand canyon west airport', 'grand forks international airport',
            'grand rapids itasca county airport', 'grant county airport', 'grant county international airport',
            'great bend municipal airport', 'great falls international airport', 'greater binghamton airport',
            'greater rochester international airport', 'greater rockford airport',
            'greenbrier valley airport', 'greenville   spartanburg airport', 'griffiss airpark',
            'groton-new london airport', 'guam international airport', 'gulfport-biloxi international airport',
            'gulkana airport', 'gunnison-crested butte regional airport', 'gustavus airport',
            'hagerstown regional airport', 'haines airport', 'hana airport', 'hancock county-bar harbor airport',
            'harrisburg international airport', 'harrison marion regional airport', 'hartford-brainard airport',
            'hattiesburg-laurel regional airport', 'hawkins field airport', 'hays regional airport',
            'hector international airport', 'helena regional airport', 'henderson executive airport',
            'henderson field airport', 'henry e rohlsen airport', 'hickory regional airport',
            'hilo international airport', 'hilton head airport', 'hobby airport', 'hollis seaplane base',
            'homer airport', 'honolulu international airport', 'hoonah airport', 'hooper bay airport',
            'houghton county memorial airport', 'huntsville international airport', 'huron regional airport',
            'huslia airport', 'huslia airport', 'hutchinson municipal airport', 'idaho falls regional airport',
            'igor i sikorsky memorial airport', 'iliamna airport', 'imperial county airport',
            'indianapolis international airport', 'inyokern airport', 'iron mountain airport',
            'ithaca tompkins regional airport', 'jack mc namara field airport', 'jackson county airport',
            'jackson hole airport', 'jackson-evers international airport', 'jacksonville international airport',
            'jacksonville albert j ellis airport', 'jamestown regional airport', 'jefferson city memorial airport',
            'john f. kennedy international airport', 'john wayne airport', 'johnstown-cambria county airport',
            'jonesboro municipal airport', 'joplin regional airport', 'juneau international airport',
            'kahului airport', 'kake airport', 'kalamazoo battle creek international airport',
            'kalskag airport', 'kaltag airport', 'kansas city international airport',
            'karl stefan memorial airport', 'kasigluk airport', 'kearney municipal airport',
            'keene dillant-hopkins airport', 'kenai municipal airport', 'kenosha regional airport',
            'ketchikan international airport', 'key field airport', 'key west international airport',
            'killeen-fort hood regional airport', 'king cove airport', 'king salmon airport',
            'kingman airport', 'kinston regional jetport', 'kipnuk airport', 'kirksville regional airport',
            'kivalina airport', 'klamath falls airport', 'klawock airport', 'knox county regional airport',
            'kodiak airport', 'kodiak municipal airport', 'kona international airport', 'kongiganak airport',
            'kotlik airport', 'koyuk airport', 'kwethluk airport', 'kwigillingok airport', 'kwigillingok airport',
            'la crosse municipal airport', 'la guardia airport', 'lafayette regional airport',
            'lake charles regional airport', 'lake havasu city airport', 'lake hood airport', 'lake tahoe airport',
            'lakefront airport', 'lakeland linder regional airport', 'lamar municipal airport',
            'lambert-st. louis international airport', 'lanai airport', 'lancaster airport',
            'lansing capital city airport', 'laramie regional airport', 'laredo international airport',
            'larsen bay airport', 'las cruces international airport', 'laughlin bullhead international airport',
            'lawton-fort sill regional airport', 'lea county regional airport', 'lebanon municipal airport',
            'lee c fine memorial airport', 'lehigh valley international airport', 'lewiston-nez perce county airport',
            'liberal municipal airport', 'lihue airport', 'lincoln airport', 'little rock national airport',
            'long beach airport', 'lorain county regional airport', 'los angeles international airport',
            'louisville international airport', 'lubbock international airport',
            'luis munoz marin international airport', 'lynchburg regional airport preston glenn field',
            'm graham clark - taney county airport', 'macarthur airport', 'magic valley regional airport',
            'mammoth yosemite airport', 'manchester airport', 'manhattan regional airport', 'manistee county-blacker',
            'mankato regional airport', 'manokotak airport', 'mansfield lahm regional airport', 'marshall airport',
            'marshall don hunter sr', 'marshall don hunter sr airport', "martha's vineyard airport",
            'mason city municipal airport', 'massena international airport', 'mayaquez airport', 'mc clellan airfield',
            'mc clellan-palomar airport', 'mc cook regional airport', 'mc kellar-sipes regional airport',
            'mc minnville municipal airport', 'mcallen-miller international airport', 'mccarran international airport',
            'mcgrath airport', 'mcghee tyson airport', 'meadows field airport',
            'medford rogue valley international airport', 'melbourne international airport', 'memorial field airport',
            'memphis airport', 'menominee-marinette twin county airport', 'merced municipal airport',
            'mercedita airport', 'merrill c meigs field', 'merrill field', 'metlakatla airport', 'miami airport',
            'miami international airport', 'mid delta regional airport', 'mid-ohio valley regional airport',
            'midamerica airport', 'middle bass island airport', 'middle georgia regional airport',
            'midland international airport', 'millington regional jetport', 'millville municipal airport',
            'minneapolis st. paul international airport', 'minot international airport',
            'missoula international airport', 'mitchell municipal airport', 'mobile regional airport',
            'modesto city-county airport', 'molokai airport', 'monmouth executive airport', 'monroe county airport',
            'monroe regional airport', 'monterey peninsula airport', 'montgomery regional airport',
            'montrose regional airport', 'moore county airport', 'morgantown municipal airport',
            'morristown municipal airport', 'morrisville-stowe state airport', 'mount comfort airport',
            'mount vernon airport', 'mountain village airport', 'muskegon county airport', 'myrtle beach airport',
            'nantucket memorial airport', 'napakiak airport', 'naples municipal airport',
            'nashville international airport', 'natrona county international airport',
            'new bedford regional airport', 'new castle airport', 'new orleans international airport',
            'newark liberty international airport', 'newport municipal airport',
            'newport news williamsburg international airport', 'newport state airport', 'newport state airport',
            'newtok airport', 'noatak airport', 'nome airport', 'norfolk international airport',
            'north bend municipal airport', 'north central state airport', 'north las vegas air terminal',
            'north platte regional airport lee bird field', 'northern maine regional airport',
            'northwest alabama regional airport', 'northwest arkansas regional airport', 'nuiqsut airport',
            'nulato airport', 'nunapitchuk airport', 'oakland county international airport',
            'oakland international airport', 'ocala international airport', 'ofu airport', 'ogden-hinckley airport',
            'ogdensburg international airport', 'ohio state university airport',
            'olathe new century aircenter airport', 'old harbor airport', 'olympia airport', 'oneida county airport',
            'ontario international airport', 'orcas island airport', 'orlando international airport',
            'orlando sanford international airport', 'ottumwa industrial airport', 'outagamie county regional airport',
            'owensboro-daviess county airport', 'oxnard airport', 'paducah barkley regional airport',
            'page municipal airport', 'pago pago international airport', 'palm beach international airport',
            'palm springs international airport', 'palmdale regional airport',
            'panama city-bay county international airport', 'pangborn memorial airport',
            'paso robles municipal airport', 'pease international airport', 'pellston regional airport',
            'pensacola regional airport', 'peoria regional airport', 'petersburg airport',
            'philadelphia international airport', 'phoenix goodyear airport',
            'phoenix sky harbor international airport', 'piedmont triad international airport',
            'pierre regional airport', 'pilot station airport', 'pinal airpark', 'pitt-greenville airport',
            'pittsburgh international airport', 'pocatello regional airport', 'point hope airport',
            'ponca city regional airport', 'port columbus international airport', 'port graham airport',
            'port heiden airport', 'port lions airport', 'porter county municipal airport',
            'portland international airport', 'portland international jetport', 'prospect creek airport',
            'provincetown municipal airport', 'provo municipal airport', 'pueblo memorial airport',
            'pullman   moscow regional airport', 'purdue university airport', 'put - in - bay airport',
            'quad city international airport', 'quincy regional airport - baldwin field', 'quinhagak airport',
            'quonset state airport', 'raleigh county memorial airport', 'raleigh-durham international airport',
            'ralph m calhoun memorial airport', 'ralph wien memorial airport', 'rapid city regional airport',
            'reading regional airport', 'redding municipal airport', 'reno-tahoe international airport',
            'republic airport', 'rhinelander-oneida county airport', 'richard b russell airport',
            'richmond international airport', 'rickenbacker international airport', 'riverton regional airport',
            'roanoke regional airport', 'robert (bob) curtis memorial airport', 'robert (bob) curtis memorial airport',
            'robert j. miller air park', 'roberts field', 'rochester international airport',
            'rock springs-sweetwater county airport', 'rocky mount-wilson regional airport',
            'ronald reagan washington national airport', 'rosecrans memorial airport',
            'roswell industrial air center airport', 'rota international airport', 'russian mission airport',
            'rutland state airport', 'sacramento international airport', 'saginaw international airport',
            'saint paul island airport', 'saipan international airport', 'salem municipal airport - mcnary field',
            'salina municipal airport', 'salisbury-ocean city wicomico regional airport',
            'salt lake city international airport', 'san angelo regional airport mathis field',
            'san antonio international airport', 'san bernardino international airport',
            'san diego international airport', 'san francisco international airport', 'san jose international airport',
            'san luis county regional airport', 'san luis valley regional airport', 'sand point airport',
            'santa barbara airport', 'santa fe municipal airport', 'santa maria public airport',
            'sarasota-bradenton international airport', 'savannah hilton head international airport',
            'savoonga airport', 'sawyer international airport', 'scammon bay airport',
            'seattle tacoma international airport', 'selawik airport', 'seldovia airport',
            'shenandoah valley regional airport', 'sheridan county airport', 'shishmaref airport',
            'show low regional airport', 'shreveport regional airport', 'shungnak airport',
            'sidney-richland municipal airport', 'sierra blanca regional airport', 'sierra vista municipal airport',
            'sioux falls regional airport', 'sioux gateway airport', 'sitka rocky gutierrez airport',
            'skagway airport', 'skylark field', 'sloulin field international airport', 'smith reynolds airport',
            'smyrna airport', 'snohomish county airport (paine field)', 'sonoma county airport',
            'south bend regional airport', 'southeast iowa regional airport', 'southeast texas regional airport',
            'southern california logistics airport', 'southern illinois airport',
            'southern wisconsin regional airport', 'southwest florida international airport',
            'southwest georgia regional airport', 'southwest michigan regional airport',
            'space coast regional airport', 'spirit of st louis airport', 'spokane international airport',
            'springfield branson regional airport', 'springfield-beckley municipal airport', 'st augustine airport',
            'st cloud regional airport', 'st george municipal airport', 'st louis regional airport',
            "st mary's airport", 'st paul downtown airport   holman field',
            'st. petersburg-clearwater international airport', 'stebbins airport', 'stewart international airport',
            'stillwater regional airport', 'stockton metropolitan airport', 'sullivan county international airport',
            'sussex county airport', 'syracuse hancock international airport', 't.f. green airport',
            'tallahassee regional airport', 'talladega municipal airport', 'tampa international airport',
            'taos regional airport', 'telluride regional airport', 'terre haute international airport',
            'teterboro airport', 'texarkana regional airport', 'thief river falls regional airport',
            'thorne bay airport', 'tinian international airport', 'togiak airport', 'toksook bay airport',
            'toledo express airport', 'trent lott international airport', 'trenton mercer airport',
            'tri-cities airport', 'tri-cities regional airport', 'tri-state airport', 'trident basin seaplane base',
            'tucson international airport', 'tulsa international airport', 'tuluksak airport',
            'tuntutuliak airport', 'tupelo regional airport', 'tuscaloosa regional airport',
            'tweed new haven regional airport', 'tyler pounds regional airport', 'unalakleet airport',
            'unalaska airport', 'university park airport', 'university-oxford airport', 'valdez pioneer field',
            'valdosta regional airport', 'valley international airport', 'venango regional airport',
            'vermilion county airport', 'vero beach municipal airport', 'vicksburg tallulah regional airport',
            'victoria regional airport', 'vieques airport', 'visalia municipal airport', 'w k kellogg airport',
            'waco regional airport', 'waimea - kohala airport', 'wainwright airport', 'walker field airport',
            'walla walla regional airport', 'washington dulles international airport', 'waterbury-oxford airport',
            'waterloo regional airport', 'watertown international airport', 'watertown municipal airport',
            'waynesville regional airport at forney field', 'west yellowstone airport', 'westchester county airport',
            'westerly state airport', 'western nebraska regional airport', 'westover metropolitan airport',
            'whiteside county airport', 'wichita falls municipal airport', 'wichita mid-continent airport',
            'wiley post-will rogers memorial airport', 'wilkes-barre scranton international airport',
            'will rogers world airport', 'william h. morse state airport', 'william r fairchild international airport',
            'williams gateway airport', 'williamson county regional airport', 'williamsport regional airport',
            'willmar municipal airport', 'wilmington international airport', 'wittman regional airport',
            'wokal field glasgow international airport', 'woodring municipal airport', 'worcester regional airport',
            'worland municipal airport', 'worthington municipal airport', 'wrangell airport',
            'yakima air terminal mcallister field', 'yakutat airport', 'yampa valley regional airport',
            'yellowstone regional airport', 'youngstown regional airport', 'yuma international airport']

airlines = [
    'alaska airlines', 'as', 'asa',
    'allegiant air', 'g4', 'aay'
    'american airlines', 'aa', 'aal',
    'delta air lines', 'dl', 'dal',
    'frontier airlines', 'f9', 'fft',
    'hawaiian airlines', 'ha', 'hal',
    'jetblue airways', 'b6', 'jbu',
    'southwest airlines', 'wn', 'swa',
    'spirit airlines', 'nk', 'nks',
    'sun country airlines', 'sy', 'scx',
    'united airlines', 'ua', 'ual',
    'air wisconsin', 'zw', 'awi',
    'cape air', '9k', 'kap',
    'commut air', 'c5', 'uca',
    'compass airlines', 'cp', 'cpz',
    'contour airlines', 'lf', 'vte',
    'elite airways', '7q', 'mnu',
    'endeavor air', '9e', 'edv',
    'envoy air', 'mq', 'eny',
    'expressjet',
    'gojet airlines',
    'horizon air',
    'mesa airlines',
    'penair',
    'piedmont airlines',
    'psa airlines',
    'republic airways',
    'silver airways',
    'skywest airlines',
    'trans states airlines'
]

airport_codes = ['abr', 'abi', 'adk', 'kki', 'aki', 'cak', 'kqa', 'auk', 'alm', 'als', 'alb', 'cvo', 'qwy', 'abq',
                 'wkk', 'aex', 'aet', 'abe', 'aia', 'apn', 'aoo', 'ama', 'abl', 'akp', 'anc', 'agn', 'ani', 'anv',
                 'atw', 'acv', 'arc', 'avl', 'hts', 'ase', 'ahn', 'akb', 'atl', 'aiy', 'atk', 'ags', 'aug', 'aus',
                 'bfl', 'bwi', 'bgr', 'bhb', 'brw', 'bti', 'btr', 'mbs', 'bpt', 'zbv', 'wbq', 'bkw', 'bed', 'blv',
                 'bli', 'bji', 'beh', 'bet', 'abe', 'btt', 'bil', 'gpt', 'bgm', 'kbc', 'bhm', 'bis', 'bid', 'bmi',
                 'blf', 'boi', 'bos', 'xhh', 'whh', 'wbu', 'bya', 'bwg', 'bzn', 'bfd', 'brd', 'bwd', 'qkb', 'tri',
                 'bkx', 'rbh', 'bro', 'bqk', 'bkc', 'buf', 'ifp', 'bur', 'brl', 'btv', 'btm', 'cak', 'cgi', 'lur',
                 'ehm', 'mdh', 'cld', 'cnm', 'mry', 'cpr', 'cdc', 'cid', 'cem', 'cdr', 'cik', 'cmi', 'chs', 'crw',
                 'clt', 'cho', 'cha', 'cyf', 'vak', 'cys', 'cgx', 'chi', 'mdw', 'ord', 'ckx', 'cic', 'kcg', 'kcq',
                 'kcl', 'czn', 'hib', 'chu', 'cvg', 'chp', 'irc', 'clp', 'ckb', 'pie', 'cle', 'cvn', 'cod', 'cfa',
                 'kcc', 'cdb', 'cll', 'cos', 'cou', 'cae', 'csg', 'gtr', 'cmh', 'ccr', 'cnk', 'qce', 'cdv', 'crp',
                 'cez', 'cga', 'cec', 'cko', 'cuw', 'cbe', ' to', 'dfw', 'day', 'dab', 'dec', 'drg', 'djn',
                 'den', 'qwm', 'dsm', 'dtt', 'dtw', 'dvl', 'dik', 'dlg', 'ddc', 'dhn', 'duj', 'dbq', 'dlh', 'dro',
                 'rdu', 'rdu', 'dut', 'abe', 'eau', 'eda', 'eek', 'kku', 'kek', 'ipl', 'eld', 'elp', 'elv', 'eli',
                 'eko', 'elm', 'lyu', 'emk', 'bgm', 'wdg', 'eri', 'esc', 'eug', 'acv', 'eue', 'evv', 'fai', 'far',
                 'fyv', 'xna', 'fay', 'flg', 'fnt', 'flo', 'msl', 'fnl', 'qwf', 'fod', 'fll', 'tbn', 'rsw', 'fsm',
                 'vps', 'fwa', 'dfw', 'fkl', 'fat', 'gnv', 'gup', 'gck', 'gyy', 'gcc', 'ggg', 'ggw', 'gdv', 'glv',
                 'gnu', 'jgc', 'gcn', 'gfk', 'gri', 'gjt', 'grr', 'gpz', 'kgx', 'gtf', 'grb', 'gso', 'glh', 'pgv',
                 'gsp', 'gon', 'gpt', 'guc', 'gst', 'hgr', 'sun', 'hns', 'phf', 'hnm', 'pak', 'cmx', 'leb', 'hrl',
                 'mdt', 'hro', 'bdl', 'hae', 'hvr', 'hdn', 'hys', 'hkb', 'hln', 'avl', 'hib', 'hky', 'gso', 'ito',
                 'hhh', 'hbb', 'hyl', 'hcr', 'hom', 'hnl', 'mkk', 'hnh', 'hpb', 'hot', 'hou', 'hou', 'iah', 'hus',
                 'hts', 'hsv', 'hon', 'hsl', 'hya', 'hyg', 'ida', 'igg', 'ili', 'ipl', 'ind', 'inl', 'iyk', 'imt',
                 'iwd', 'isp', 'ith', 'jac', 'jan', 'mkl', 'jax', 'oaj', 'jms', 'jhw', 'jvl', 'bgm', 'tri', 'jst',
                 'jbr', 'jln', 'jnu', 'ogg', 'kae', 'knk', 'azo', 'lup', 'klg', 'kal', 'mue', 'mci', 'jhm', 'kxa',
                 'kuk', 'lih', 'ear', 'een', 'ena', 'ktn', 'eyw', 'qks', 'ian', 'ggg', 'ile', 'kvc', 'akn', 'igm',
                 'tri', 'kpn', 'irk', 'kvl', 'lmt', 'klw', 'tys', 'obu', 'adq', 'koa', 'kkh', 'kot', 'otz', 'kyu',
                 'kwt', 'kwk', 'lse', 'laf', 'lft', 'lch', 'hii', 'lma', 'lny', 'lns', 'lan', 'lar', 'lrd', 'las',
                 'lbe', 'pib', 'law', 'leb', 'kll', 'lwb', 'lws', 'lwt', 'lex', 'lbl', 'lih', 'lnk', 'lit', 'lgb',
                 'ggg', 'lps', 'lax', 'sdf', 'nl)', 'qwf', 'lbb', 'mcn', 'msn', 'mdj', 'mht', 'mhk', 'mbl', 'mkt',
                 'mly', 'kmo', 'pkb', 'mwa', 'mqt', 'mll', 'mvy', 'aoo', 'mcw', 'mss', 'ogg', 'mfe', 'mck', 'mcg',
                 'mfr', 'myu', 'mlb', 'mem', 'mce', 'mei', 'mtm', 'wmk', 'mia', 'mpb', 'mbs', 'maf', 'mls', 'mke',
                 'msp', 'mot', 'mnt', 'mfe', 'mso', 'cny', 'mob', 'mod', 'mli', 'mlu', 'mry', 'mgm', 'mtj', 'mgw',
                 'mwh', 'wmh', 'mou', 'msl', 'mkg', 'myr', 'ack', 'wna', 'pka', 'apf', 'bna', 'nki', 'nlg', 'ncn',
                 'hvn', 'kgk', 'gon', 'msy', 'knw', 'nyc', 'jfk', 'lga', 'ewr', 'swf', 'phf', 'wwt', 'nme', 'nib',
                 'iko', 'wtk', 'ome', 'nnl', 'orv', 'ofk', 'orf', 'oth', 'lbf', 'ort', 'nui', 'nul', 'nup', 'oak',
                 'maf', 'ogs', 'okc', 'oma', 'ont', 'sna', 'orl', 'mco', 'osh', 'otm', 'owb', 'oxr', 'pah', 'pga',
                 'psp', 'pfn', 'pkb', 'psc', 'pdb', 'pec', 'pln', 'pdt', 'pns', 'pia', 'kpv', 'psg', 'phl', 'ttn',
                 'phx', 'pir', 'ugb', 'pip', 'pqs', 'pit', 'ptu', 'plb', 'pih', 'kpb', 'pho', 'piz', 'pnc', 'pse',
                 'pta', 'clm', 'bpt', 'kpc', 'pth', 'pml', 'ppv', 'pca', 'pwm', 'pdx', 'psm', 'pou', 'prc', 'pqi',
                 'blf', 'pvd', 'pvc', 'scc', 'pub', 'puw', 'uin', 'kwn', 'rdu', 'rmp', 'rap', 'rdg', 'rdv', 'rdd',
                 'rdm', 'rno', 'rhi', 'ric', 'riw', 'roa', 'rce', 'rst', 'roc', 'rks', 'zrf', 'zrk', 'rkd', 'rsj',
                 'row', 'rby', 'rsh', 'rut', 'smf', 'mbs', 'stc', 'stg', 'sgu', 'stl', 'ksm', 'smk', 'snp', 'sle',
                 'sln', 'sby', 'slc', 'sjt', 'sat', 'san', 'sfo', 'sjc', 'sju', 'sbp', 'sdp', 'sna', 'sba', 'saf',
                 'smx', 'sts', 'slk', 'srq', 'ciu', 'sav', 'sva', 'scm', 'bff', 'sdl', 'avp', 'lke', 'sea', 'wlk',
                 'swd', 'shx', 'skk', 'msl', 'sxp', 'shr', 'shh', 'shv', 'shg', 'svc', 'sux', 'fsd', 'sit', 'sgy',
                 'slq', 'sbn', 'wsn', 'sop', 'gsp', 'geg', 'spi', 'sgf', 'pie', 'sce', 'shd', 'sbs', 'wbb', 'cwa',
                 'svs', 'swf', 'sck', 'srv', 'sun', 'syr', 'tct', 'tka', 'tlh', 'tpa', 'tal', 'tsm', 'tek', 'kts',
                 'tex', 'tke', 'huf', 'teh', 'txk', 'tvf', 'ktb', 'tnc', 'tog', 'tkj', 'ook', 'tol', 'foe', 'tvc',
                 'ttn', 'tus', 'tul', 'tlt', 'wtl', 'tnk', 'tup', 'tcl', 'twf', 'twa', 'tyr', 'unk', 'cmi', 'uca',
                 'uto', 'ege', 'qbf', 'vdz', 'vld', 'vps', 'vee', 'oxr', 'vel', 'vct', 'vis', 'act', 'ain', 'waa',
                 'alw', 'was', 'iad', 'dca', 'kwf', 'alo', 'art', 'aty', 'cwa', 'eat', 'pbi', 'wys', 'hpn', 'wst',
                 'wsx', 'wwp', 'wmo', 'leb', 'sps', 'ict', 'avp', 'phf', 'ipt', 'isn', 'ilm', 'bdl', 'orh', 'wrl',
                 'wrg', 'ykm', 'yak', 'cod', 'yng', 'yum']


state_name = ['alabama ', 'alaska ', 'arizona ', 'arkansas ', 'california ', 'colorado ', 'connecticut ', 'delaware ',
              'florida ', 'georgia ', 'hawaii ', 'idaho ', 'illinois indiana ', 'iowa ', 'kansas ', 'kentucky ',
              'louisiana ', 'maine ', 'maryland ', 'massachusetts ', 'michigan ', 'minnesota ', 'mississippi ',
              'missouri ', 'montana nebraska ', 'nevada ', 'new hampshire ', 'new jersey ', 'new mexico ',
              'new york ', 'north carolina ', 'north dakota ', 'ohio ', 'oklahoma ', 'oregon ', 'pennsylvania',
              'rhode island ', 'south carolina ', 'south dakota ', 'tennessee ', 'texas ', 'utah ', 'vermont ',
              'virginia ', 'washington ', 'west virginia ', 'wisconsin ', 'wyoming']


state_code = ['al', 'ak', 'az', 'ar', 'ca', 'co', 'ct', 'de', 'fl', 'ga', 'hi', 'id', 'il', 'in', 'ia', 'ks', 'ky',
              'la', 'me', 'md', 'ma', 'mi', 'mn', 'ms', 'mo', 'mt', 'ne', 'nv', 'nh', 'nj', 'nm', 'ny', 'nc', 'nd',
              'oh', 'ok', 'or', 'pa', 'ri', 'sc', 'sd', 'tn', 'tx', 'ut', 'vt', 'va', 'wa', 'wv', 'wi', 'wy']

meal = ['meal', 'meals']

meal_desc = ['breakfast', 'lunch', 'dinner']

flight_mod = ['weekdays', 'only-weekdays', 'weekday']

if __name__ == '__main__':
    pass
